# Generated by Django 5.0.2 on 2024-03-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_DB',
            fields=[
                ('slno', models.IntegerField(primary_key='slno', serialize=False)),
                ('bname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('published_date', models.DateField()),
                ('prize', models.IntegerField()),
            ],
        ),
    ]
